### ISSUE TITLE
PTFE Dashboard always selects `S3` option for storage type, despite specifying Azure Storage in `replicated-ptfe.conf`

### ISSUE THREAD

**Issue by shiro105** [hashicorp/terraform-azurerm-terraform-enterprise#11]
# Issue
I am encountering an issue with the PTFE Dashboard where once I `terraform apply` the module specified here, the Settings page will always incorrectly select `S3` for the storage type, even when I have not filled out any settings in the `replicated-ptfe.conf` pertaining to AWS S3. 

# Outcome
As such, this causes the PTFE installation to be halted because the application believes it is utilizing AWS S3 for its external storage, when it was actually configured to use Azure's Storage Accounts. The only way to resume the application starting up is to manually go into the settings and selecting `Azure` as the storage type and saving the settings in order for the application to finish properly spinning up.

**Comment by amy-hashi** [comment]
Thanks for the issue. Fix will be PR'd shortly and will be in the next release. In the interim, you can point your module directly to github instead of the registry if you want.

**Comment by shiro105** [comment]
@amy-hashi Thanks for the quick fix! I just did a quick check on my end on the fix and it seems to have fixed the issue I was running into. 👍 I will go ahead and close this issue now. If anything else comes up from this, I'll go ahead and make another issue.
