### ISSUE TITLE
When using a RedHat 7.6 VM, `install-ptfe.sh` fails early

### ISSUE THREAD

**Issue by shiro105** [hashicorp/terraform-azurerm-terraform-enterprise#15]
# Specs
RedHat 7.6 (RHEL 7-RAW-CI version 7.6.2019.072418)

# Issue
When I was trying out the module using RedHat 7.6, upon executing `terraform apply` on the module, I noticed that in the logs for `/var/log/cloud-init-output.log`, the script, `install-ptfe.sh` fails at line 25:

```
sed -i -e '/rhui-REGION-rhel-server-extras/,/^$/s/enabled=0/enabled=1/g'  /etc/yum.repos.d/redhat-rhui.repo
```

The error that pops up is:

```
sed: can't read /etc/yum.repos.d/redhat-rhui.repo: No such file or directory
```

Upon looking in that folder, the `redhat-rhui.repo` is missing in `/etc/yum.repos.d`. Is there something I am missing in this? I did not do any prior modifications to the VM, since I presumed the `install-ptfe.sh` script would take care of that.

# Outcome
Because the script fails early, the cluster does not form, making the installation of PTFE using a RedHat VM image not work properly.

**Comment by amy-hashi** [comment]
@shiro105 I've merged a fix into master for this. 

I'll be working on a better fix next week that will support airgap, but this fix should allow you to continue beta testing.

**Comment by shiro105** [comment]
@amy-hashi Sorry for the late reply, but I got around to test out your changes and I can confirm that the script was able to proceed past the point I outlined in the issue. 😃 Thanks for the update!

However, another issue sprang up in that the script would time out before the cluster is initialized. 
```
...
[wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests". This cab take up to 4m0s
[kubelet-check] Initial timeout of 40s

Unfortunately, an error has occurred:
        timed out waiting for the condition

This error is likely caused by:
        - The kubelet is not running
        - The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)

If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
        - 'systemctl status kubelet'
        - 'journalctl -xeu kubelet'

Additionally, a control plane component may have crashed or exited when started by the container runtime.
To troubleshoot, list all containers using your preferred container runtimes CLI, e.g. docker.
Here is one example how you may list all Kubernetes containers running in docker:
        - 'docker ps -a | grep kube | grep -v pause'
        Once you have found the failing container, you can inspect its logs with:
        - 'docker logs CONTAINERID'
error execution phase wait-control plane: couldn't initialize a Kubernetes cluster
```

The reasoning has to do with the internal firewall, `firewalld` was enabled by default on the VM image I am using. With this firewall on, it prevented the VM from having any outward access to the endpoints that the cluster would spin up. A quick workaround is to disable and stop this firewall by running the following on the VMs:
```
service firewalld stop
systemctl disable firewalld
```

Once I ran those lines, the script completed successfully and I got a working cluster up! 😄 

While those commands could be tacked onto the install script, I think this is something that could vary with what RedHat image users use. At the same time, however, if one were to run this module using a standard vanilla RedHat image, the installation will still fail. As such, adding those calls to the install script could be beneficial. In my case, I was using the **base Azure RedHat 7.6 image**, so the firewall had to be turned off prior to the `ptfe install ...` line. 

Do you have any thoughts on this? Otherwise, this issue can be closed now.

**Comment by shiro105** [comment]
In the new release for 0.1.0, the fix that @amy-hashi did was undone by @erindatkinson's commit. Not sure if that was intentional, but as of now, the module no longer works with RedHat VMs. The line was specifically:

```
  sed -i -e '/rhui-REGION-rhel-server-extras/,/^$/s/enabled=0/enabled=1/g'  /etc/yum.repos.d/redhat-rhui.repo
  yum -y install docker wget jq chrony ipvsadm unzip
  # remove after testing rhui?
  # curl -sfSL -o /usr/bin/jq https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64
  # chmod +x /usr/bin/jq
```
where the line above the `yum` call was readded in. A temporary fix for this was I forked the repository and removing said line and commentating out the bottom two lines.
