### ISSUE TITLE
terraform 0.12.9 issue with license file

### ISSUE THREAD

**Issue by steku** [hashicorp/terraform-azurerm-terraform-enterprise#16]
Error: Error in function call

  on modules/configs/cloud-init.tf line 70, in data "template_file" "cloud_config":
  70:     license_b64          = "${base64encode(file("${var.license_file}"))}"
    |----------------
    | var.license_file is "/Users/steve/projects/client/capco/terraform-azurerm-terraform-enterprise/creds/partner-arctiq.rli"

Call to function "file" failed: contents of
partner-arctiq.rli
are not valid UTF-8; use the filebase64 function to obtain the Base64 encoded
contents or the other file functions (e.g. filemd5, filesha256) to obtain file
hashing results instead.

**Comment by evanphx** [comment]
@steku What terraform version were you using?

**Comment by steku** [comment]
12.9

**Comment by evanphx** [comment]
0.12.9 I presume you mean?

**Comment by steku** [comment]
yes

**Comment by evanphx** [comment]
Right now we only support 0.11. We're working on 0.12 support at the moment.

**Comment by evanphx** [comment]
Regardless, thank you for opening this issue, we'll be sure to get it handled as we make the modules 0.12 compliant

**Comment by steku** [comment]
Thanks

**Comment by ausfestivus** [comment]
Some thing occurs with the certificate.pfx file for the Azure deploy.

**Comment by ausfestivus** [comment]
Hey @steku there is v 0.12.x code in master now. Want to try again and see if this problem is persisting?

**Comment by bnferguson** [comment]
Closing this for now as @ausfestivus said there's now 0.12.x code in master and this should no longer be a problem. Feel free to reopen if you still see the issue. (and thanks for looking out @ausfestivus!)
