### ISSUE TITLE
Trouble in automating the initial admin creation via the API

### ISSUE THREAD

**Issue by shiro105** [hashicorp/terraform-azurerm-terraform-enterprise#18]
# Issue
I am running into a strange issue when trying to automate the creation of the initial admin user as documented [here](https://www.terraform.io/docs/enterprise/install/automating-initial-user.html#via-api). I specified the `iact_subnet_list` to be a single CIDR block (eg. `"XXX.XXX.0.0/16"`) and the `iact_subnet_time_limit`as `"unlimited"`, but after each time I got the installation to the dashboard, I was still unable to create the admin user. I made sure my IP that I am running the `curl` call is within the CIDR block range I specified in the `iact_subnet_list`.

The only clue I found when using`/admin/retrieve-iact` was when I added `-v` to `curl`:

```
$ curl -vks https://domain.com/admin/retrieve-iact

HTTP/1.1 401 Unauthorized
Server: nginx/1.17.1
Date: Wed 25 Sep 2019 23:50:37 GMT
Content-Type: text/html; charset=utf-8
Connection: keep-alive
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Cache-Control: nocache
X-Request-Id: ...
Vary: origin
```

Do I need to specify some form of authentication in the `curl` call? From my understanding of the API documentation, there is no mention of requiring any authorization to call on this API endpoint. Is there something I am missing?

**Comment by evanphx** [comment]
Hi @shiro105,

Did you double check that the client does fall within the given CIDR block? Even if there is a proxy between the client and the server in the CIDR block, it will use the client's true IP. To check, you can also just set that to 0.0.0.0/0 and see if you can access the API.

**Comment by shiro105** [comment]
@evanphx Ah ok that does make a lot of sense. I am behind a proxy, which does shed some light to the situation. Is this a specific nuance that occurs with replicated?

Regardless, by filling in `0.0.0.0/0` in the `iact_subnet_list` in the module, I was able to access the API token creation from the machine I am working from. So the issue boiled down to the CIDR range not being correct on my end. Thanks again for clarifying! I will go ahead and close this issue.

**Comment by evanphx** [comment]
No, nothing related to replicated. Your proxy is passing through the true client IP address and we're honoring it to decide if we should allow access to the IACT api.
