### ISSUE TITLE
An input variable with the name "install_type" has not been declared.

### ISSUE THREAD

**Issue by lhaig** [hashicorp/terraform-azurerm-terraform-enterprise#19]
# Environment
TF 0.12.9
module version 0.0.3

# Description 

When running the new version of the module I get the following error

Error: Reference to undeclared input variable

  on .terraform/modules/terraform_enterprise/hashicorp-terraform-azurerm-terraform-enterprise-b84933b/modules/primaries/vms.tf line 5, in resource "azurerm_virtual_machine" "primary":
   5:   count                        = "${var.install_type == "ipm" ? 3 : var.vm["count"]}"

An input variable with the name "install_type" has not been declared. This
variable can be declared with a variable "install_type" {} block.

**Comment by erindatkinson** [comment]
I def didn't catch this on that review,

one caveat, the modules are not updated for use with `0.12.X` versions of Terraform yet.

**Comment by erindatkinson** [comment]
This was fixed with the merge of https://github.com/hashicorp/terraform-azurerm-terraform-enterprise/pull/20 and will be included in the next release version.
