### ISSUE TITLE
install-ptfe.sh fails to complete the install of Kubernetes when running 

### ISSUE THREAD

**Issue by lhaig** [hashicorp/terraform-azurerm-terraform-enterprise#21]
# Environment
Terraform 11
OSX

# Bug
When deploying using the master branch the Infra deployment completes but the install script fails.

When digging further into the systems I found this error when running install-ptfe.sh file

```
2.6.2: Pulling from library/registry
Digest: sha256:6cab8c43c5288e6efa87df48019ccf6148def11e6de6fafd8e5270c2b4cdba0e
Status: Image is up to date for registry:2.6.2
✔ CNI configured
⚙  generate kubernetes bootstrap token
Kubernetes bootstrap token: 71i8fy.5c1ijjjdr0rde5nl
This token will expire in 24 hours
⚙  Verify Kubelet
⚙  Initialize Kubernetes
modprobe: FATAL: Module nf_conntrack_ipv4 not found in directory /lib/modules/5.0.0-1018-azure
2019-10-02T13:31:02.318Z [INFO]  Configured system
2019-10-02T13:31:02.318Z [TRACE] setup/setup-script-finished
2019-10-02T13:31:02.318Z [ERROR] error running setup: error="exit status 1"
```

**Comment by lhaig** [comment]
It seems like it is a kubernetes issue I found this reference 

https://github.com/kubernetes/kubernetes/issues/70304

**Comment by shiro105** [comment]
@lhaig I ran into this issue as well when I was running this module on my end. What OS was the VM that was initializing this? If you were using Ubuntu, I found a workaround by using `ubuntu 16.04 LTS` since that still has the `ip_conntrack_ipv4` module in it.

**Comment by lhaig** [comment]
Hi @amy-hashi I did not select any image It was the default as provided by the module.
I will try with an older version of ubuntu.

**Comment by lhaig** [comment]
Ok that worked @amy-hashi I have been able to get the install to complete now.
