### ISSUE TITLE
broken link in basic example README

### ISSUE THREAD

**Issue by ausfestivus** [hashicorp/terraform-azurerm-terraform-enterprise#39]
Problem:

The URL on line #3 of https://github.com/hashicorp/terraform-azurerm-terraform-enterprise/blob/master/examples/basic/README.md 404s.

Line #3 of the above README says
```
This is a basic example of how to set up the configurations to use this module. Please see the [inputs page](https://registry.terraform.io/modules/terraform-enterprise/azurerm/?tab=inputs) for more details on usage.
```
The URL on that line 404s.

Recreate:
* Browse to https://github.com/hashicorp/terraform-azurerm-terraform-enterprise/blob/master/examples/basic/README.md.
* Click the link `inputs page` to go to https://registry.terraform.io/modules/terraform-enterprise/azurerm?tab=inputs
* `inputs page` URL doesnt exist and 404s.

**Comment by bnferguson** [comment]
Ah! Thank you for this. Good catch. Have a fix going in #40.
