### ISSUE TITLE
add a mechanism for users to specify tags

### ISSUE THREAD

**Issue by ausfestivus** [hashicorp/terraform-azurerm-terraform-enterprise#42]
The Azure Subscription I am piloting in requires specific tags to be placed on all resources.
There doesnt appear to be a mechanism to allow me to specific my own tags to attach to resources when this is built.

**Comment by erindatkinson** [comment]
that's a great addition! thanks for pointing it out!

**Comment by ausfestivus** [comment]
Hey @erindatkinson any thoughts on the PR attached to this?
