### ISSUE TITLE
Not clear that PFX certificate must be converted to base64

### ISSUE THREAD

**Issue by scarolan** [hashicorp/terraform-azurerm-terraform-enterprise#44]
The variable description calls for the path to a PFX certificate:
tls_pfx_certificate string
Description: The path to a PFX certificate for front end SSL communication.

But if you try to use the binary pfx file the following error results:

```
Call to function "file" failed: contents of hashidemosio.pfx are not valid
UTF-8; use the filebase64 function to obtain the Base64 encoded contents or
the other file functions (e.g. filemd5, filesha256) to obtain file hashing
results instead.
```

Encoding the pfx file as base64 and pointing to that instead seems to resolve the issue.

**Comment by erindatkinson** [comment]
Hi! a couple quick questions! what version of the following are you running?

- Terraform
- AzureRM provider
- This module

Thanks!

**Comment by scarolan** [comment]
This appears to be an 0.12 issue.
