### ISSUE TITLE
Setup Issue Template

### ISSUE THREAD

**Issue by ausfestivus** [hashicorp/terraform-azurerm-terraform-enterprise#52]
Folks,

Time to inject an issue template into this repo. The [Azure Provider](https://github.com/terraform-providers/terraform-provider-azurerm/issues) template is a good one.

**Comment by wwsean08** [comment]
Looks like it's template is blank, though I agree a template is a good idea.

**Comment by ausfestivus** [comment]
The Org Templates for the Azure Provider are available as MD here https://github.com/terraform-providers/terraform-provider-azurerm/tree/master/.github/ISSUE_TEMPLATE

**Comment by wwsean08** [comment]
Ah ok I just went to https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/.github/ISSUE_TEMPLATE.md and didn't notice the ISSUE_TEMPLATE directory, my bad.

**Comment by bnferguson** [comment]
Great idea! And 🎉 this issue is fixed with https://github.com/hashicorp/terraform-azurerm-terraform-enterprise/pull/61
