### ISSUE TITLE
Default storage_image should be ubuntu 18.04

### ISSUE THREAD

**Issue by wwsean08** [hashicorp/terraform-azurerm-terraform-enterprise#53]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Ubuntu 18.04 has been the current LTS version of ubuntu for over a year now, so unless there's a technical reason this can't be used (I couldn't see one), I propose updating the default to 18.04.

### New or Affected Resource(s)

* All VMs created by this module

### Potential Terraform Configuration

No real change here

### References

* Pull request #54

**Comment by evanphx** [comment]
There was a strange compatibility issues seen with 18.04 on Azure early in testing which is why we opted to default to 16.04. We'll work against the PR to validate it.

**Comment by wwsean08** [comment]
Sounds good, I'm in the middle of validating it right now as well since I'm working on spinning up TFE.
