### ISSUE TITLE
virtual_network_resource_group

### ISSUE THREAD

**Issue by pearcec** [hashicorp/terraform-azurerm-terraform-enterprise#67]
There is an option for a separate resource group for the keyvault and DNS zone, but one doesn't exist for virtual network resources. For our organization we create VNETs separate from project deployments.  I am going to work on the code to make this happen and submit a pull request when done.  Is there anything I need to take under advisement?  Also I don't see any unit testing other than basic validation with terraform code.   Am I missing anything?

**Comment by bnferguson** [comment]
Hi there! Thanks for taking a look at this! 

I'd hold off a couple weeks if you can. This module is in the process of being reworked into something a bit more simple in the base case and composable in more advanced cases. To get an idea where we're going with it the GCP reroll gives some pointers. ( https://github.com/hashicorp/terraform-google-terraform-enterprise/pull/38 ) 

This work is starting this week and hopefully should have some WIP PRs going soon. If you can't hold off, go for it and we'll try to take the PR into account as we rework things! 

As for testing, currently indeed that's the only bit of automated testing we have going in this repository. We have some private things we do to test user PRs but are in the process of working out something more public on these modules as the current system is less than ideal.

**Comment by pearcec** [comment]
The code change is pretty simple.  I need it to get started. I will likely post it in case anyone else needs it in the meantime.  Otherwise I won't have an expectation of you integrating it.  Thanks for the feedback.

**Comment by adamyager** [comment]
@bnferguson bnferguson great news on the module refresh. We are just getting ready to do a fresh TFE install and saw this. Do you have an estimated release? 


> Hi there! Thanks for taking a look at this!
> 
> I'd hold off a couple weeks if you can. This module is in the process of being reworked into something a bit more simple in the base case and composable in more advanced cases. To get an idea where we're going with it the GCP reroll gives some pointers. ( [hashicorp/terraform-google-terraform-enterprise#38](https://github.com/hashicorp/terraform-google-terraform-enterprise/pull/38) )
> 
> This work is starting this week and hopefully should have some WIP PRs going soon. If you can't hold off, go for it and we'll try to take the PR into account as we rework things!
> 
> As for testing, currently indeed that's the only bit of automated testing we have going in this repository. We have some private things we do to test user PRs but are in the process of working out something more public on these modules as the current system is less than ideal.

**Comment by sijday** [comment]
This needs to be resolved ASAP the template appears to imply it will deploy resources and associate them with an existing VNet. 
However the current behaviour deploys a duplicate VNet into the resource group defined for the Terraform cluster. 
It's a mess.

**Comment by bnferguson** [comment]
> great news on the module refresh. We are just getting ready to do a fresh TFE install and saw this. Do you have an estimated release?

@adamyager - Unfortunately not! We're still working with the Google one and trying to work out kinks to make sure that it's useful both as a starting point and as something more complicated setups can use. 

@sijday - Thanks for the feedback! We'll keep an eye out for that in the refresh of these modules. For now I've merged the PR related to this so the `master` branch has it to hopefully help with this issue (you'll have to use the git version for now as there's not a new release however).
