### ISSUE TITLE
Thank you! ❤️

### ISSUE THREAD

**Issue by ausfestivus** [hashicorp/terraform-azurerm-terraform-enterprise#89]
Just putting a quick thank you note here to say thank you for bringing this module back to life.
It has languished for a good long while and it needed some love. ❤️

**Comment by glasner** [comment]
Thanks for the comment Andrew 🙏  We agree it's been a long time coming and are very exited to get this new version into beta. This new version can install Terraform Enterprise in either our Standalone or Active/Active architectures. The latter being our replacement for our previous clustering architecture. 

Would love to have you give them a spin if you have a minute. Please note, they should not be used for a production installation while we are beta. 

To the future 🚀
