### ISSUE TITLE
how to enable "Storage account key access" for Azure blob storage account with Terraform

### ISSUE THREAD

**Issue by immarvin** [hashicorp/terraform-azurerm-terraform-enterprise#95]
Hi, 

I created a azure blob storage account with following tf:
```
resource "azurerm_storage_account" "main" {
  name                     = "${var.prefix}${var.env}${var.location}brs"
  resource_group_name      = var.resource_group_name
  location                 = var.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
  account_kind             = "StorageV2"
  #delete_retention_policy = 365

  tags = {
    source   = "terraform"
    env      = var.env
    location = var.location
    owner    = "xxx@yyy.com"
  }
}

```
after I ran `terraform apply`, the "Storage account key access" is disabled by default, 

![image](https://user-images.githubusercontent.com/5668922/117945170-a5732e00-b340-11eb-9088-6cdc0bf2b59c.png)

I went through the doc https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_account, but cannot find any filed to enable "Storage account key access".

Any way to enable it with terraform? thanks

**Comment by aaron-lane** [comment]
Hi @immarvin! Unfortunately, this is the repository for the Terraform module that deploys Terraform Enterprise on Azure. Based on your question, I believe that you want to post your issue to the repository for the Azure Resource Manager provider: https://github.com/terraform-providers/terraform-provider-azurerm.
